#define MENU 0  	/* TREE */
#define SOUBORT 4  	/* OBJECT in TREE #0 */
#define OTEVRI 22  	/* OBJECT in TREE #0 */
#define OZAVRI 28  	/* OBJECT in TREE #0 */
#define KONECI 37  	/* OBJECT in TREE #0 */
#define PROHODI 85  	/* OBJECT in TREE #0 */
#define VYBERI 84  	/* OBJECT in TREE #0 */
#define RAMEA 32  	/* STRING */
#define EFORMA 35  	/* STRING */
#define EKFORMA 36  	/* STRING */
#define VYBERD 3  	/* TREE */
#define SELBAK 10  	/* OBJECT in TREE #3 */
#define SELCANB 6  	/* OBJECT in TREE #3 */
#define OKNAT 9  	/* OBJECT in TREE #0 */
#define ULOZDOI 27  	/* OBJECT in TREE #0 */
#define ULOZI 26  	/* OBJECT in TREE #0 */
#define PISNEFS 0		/* FREE STRING */
#define SEKVFS 3		/* FREE STRING */
#define SEKVZFS 2		/* FREE STRING */
#define IERRA 37  	/* STRING */
#define CLOSEA 40  	/* STRING */
#define PANIKA 34  	/* STRING */
#define RAMRA 31  	/* STRING */
#define NOKNA 45  	/* STRING */
#define OKNAFS 13		/* FREE STRING */
#define VYBOKFS 14		/* FREE STRING */
#define TONINAD 4  	/* TREE */
#define POVCANB 7  	/* OBJECT in TREE #4 */
#define POVELYT 8  	/* OBJECT in TREE #0 */
#define NOVSEKD 13  	/* TREE */
#define NSEKVE 3  	/* OBJECT in TREE #13 */
#define NSOKB 4  	/* OBJECT in TREE #13 */
#define NSCANB 5  	/* OBJECT in TREE #13 */
#define ZHLASA 46  	/* STRING */
#define RAMPA 33  	/* STRING */
#define VYVSEKFS 4		/* FREE STRING */
#define REKURA 47  	/* STRING */
#define TAKTD 5  	/* TREE */
#define TAKTCANB 13  	/* OBJECT in TREE #5 */
#define TAKTOKB 12  	/* OBJECT in TREE #5 */
#define THORDB 4  	/* OBJECT in TREE #5 */
#define TDOLHB 10  	/* OBJECT in TREE #5 */
#define TDOLDB 8  	/* OBJECT in TREE #5 */
#define THORHB 6  	/* OBJECT in TREE #5 */
#define THORT 5  	/* OBJECT in TREE #5 */
#define TDOLT 9  	/* OBJECT in TREE #5 */
#define ATTRIBD 12  	/* TREE */
#define BECKOBB 4  	/* OBJECT in TREE #12 */
#define KRIZEKBB 5  	/* OBJECT in TREE #12 */
#define ODRAZBB 6  	/* OBJECT in TREE #12 */
#define ATTROKB 15  	/* OBJECT in TREE #12 */
#define PREDTI 82  	/* OBJECT in TREE #0 */
#define ZTONINAI 80  	/* OBJECT in TREE #0 */
#define ZTAKTI 78  	/* OBJECT in TREE #0 */
#define ZTEMPOI 79  	/* OBJECT in TREE #0 */
#define NASTRFS 5		/* FREE STRING */
#define NASTRTFS 10		/* FREE STRING */
#define NOVYFS 11		/* FREE STRING */
#define TEMPOD 6  	/* TREE */
#define TEMPOKB 11  	/* OBJECT in TREE #6 */
#define TEMPCANB 12  	/* OBJECT in TREE #6 */
#define WERRA 38  	/* STRING */
#define VSEHLAI 73  	/* OBJECT in TREE #0 */
#define NHLASI 48  	/* OBJECT in TREE #0 */
#define ZHLASI 49  	/* OBJECT in TREE #0 */
#define HLASYT 5  	/* OBJECT in TREE #0 */
#define TAKTI 75  	/* OBJECT in TREE #0 */
#define TEMPOI 76  	/* OBJECT in TREE #0 */
#define TONINAI 77  	/* OBJECT in TREE #0 */
#define ZADVYSB 7  	/* OBJECT in TREE #12 */
#define TRIOLAB 11  	/* OBJECT in TREE #12 */
#define TECKAB 12  	/* OBJECT in TREE #12 */
#define ATTRCANB 14  	/* OBJECT in TREE #12 */
#define ZADDELB 10  	/* OBJECT in TREE #12 */
#define REPETD 15  	/* TREE */
#define REPCANB 8  	/* OBJECT in TREE #15 */
#define REPHB 6  	/* OBJECT in TREE #15 */
#define REPDB 5  	/* OBJECT in TREE #15 */
#define EDITFS 7		/* FREE STRING */
#define USPORI 86  	/* OBJECT in TREE #0 */
#define BLKOPI 40  	/* OBJECT in TREE #0 */
#define BLMAZI 39  	/* OBJECT in TREE #0 */
#define BLVLOZI 41  	/* OBJECT in TREE #0 */
#define NAZEXA 50  	/* STRING */
#define CENNASA 52  	/* STRING */
#define PHLASI 50  	/* OBJECT in TREE #0 */
#define JINYFS 12		/* FREE STRING */
#define SELDELB 3  	/* OBJECT in TREE #3 */
#define SELRENB 4  	/* OBJECT in TREE #3 */
#define SELOKB 7  	/* OBJECT in TREE #3 */
#define HLASITD 7  	/* TREE */
#define HLASCANB 10  	/* OBJECT in TREE #7 */
#define SELNOVB 5  	/* OBJECT in TREE #3 */
#define HRAJD 18  	/* TREE */
#define HRAVYS1T 3  	/* OBJECT in TREE #18 */
#define HRAPIST 1  	/* OBJECT in TREE #18 */
#define HRADELT 15  	/* OBJECT in TREE #18 */
#define TEMPDB 4  	/* OBJECT in TREE #6 */
#define TEMPHB 7  	/* OBJECT in TREE #6 */
#define TMPBKGB 5  	/* OBJECT in TREE #6 */
#define TMPSLDB 6  	/* OBJECT in TREE #6 */
#define HLAST 9  	/* OBJECT in TREE #7 */
#define HLASOKB 11  	/* OBJECT in TREE #7 */
#define HLASBKGB 5  	/* OBJECT in TREE #7 */
#define HLASSLDB 6  	/* OBJECT in TREE #7 */
#define HLASDB 4  	/* OBJECT in TREE #7 */
#define HLASNB 7  	/* OBJECT in TREE #7 */
#define RENAMEFS 8		/* FREE STRING */
#define BLKTAKTI 42  	/* OBJECT in TREE #0 */
#define DELFS 9		/* FREE STRING */
#define SELTLACB 2  	/* OBJECT in TREE #3 */
#define IOERRA 39  	/* STRING */
#define NPOVA 48  	/* STRING */
#define ERRORA 44  	/* STRING */
#define REPOKB 9  	/* OBJECT in TREE #15 */
#define OKTAVAD 8  	/* TREE */
#define OKTDB 4  	/* OBJECT in TREE #8 */
#define OKTNB 5  	/* OBJECT in TREE #8 */
#define OKTT 6  	/* OBJECT in TREE #8 */
#define OKTOKB 9  	/* OBJECT in TREE #8 */
#define OKTCANB 10  	/* OBJECT in TREE #8 */
#define CISTFS 1		/* FREE STRING */
#define VYVSEKI 69  	/* OBJECT in TREE #0 */
#define NASTROJI 63  	/* OBJECT in TREE #0 */
#define HLASITI 64  	/* OBJECT in TREE #0 */
#define OKTAVAI 66  	/* OBJECT in TREE #0 */
#define PRIKAZT 7  	/* OBJECT in TREE #0 */
#define ZACREPI 70  	/* OBJECT in TREE #0 */
#define KONREPI 71  	/* OBJECT in TREE #0 */
#define CEZREPA 53  	/* STRING */
#define CEKREPA 54  	/* STRING */
#define NPREPA 49  	/* STRING */
#define EDNASD 16  	/* TREE */
#define EDNSOU1T 6  	/* OBJECT in TREE #16 */
#define EDNSOU2T 7  	/* OBJECT in TREE #16 */
#define EDNASTT 3  	/* OBJECT in TREE #16 */
#define EDNSOUBB 4  	/* OBJECT in TREE #16 */
#define NAZPOVA 51  	/* STRING */
#define TOOLBOX 1  	/* TREE */
#define DSKTONB 1  	/* OBJECT in TREE #1 */
#define DSKTAKTB 2  	/* OBJECT in TREE #1 */
#define DSKTEMPB 4  	/* OBJECT in TREE #1 */
#define DSKREPB 7  	/* OBJECT in TREE #1 */
#define DSKCTIB 10  	/* OBJECT in TREE #1 */
#define DSKEDITB 3  	/* OBJECT in TREE #1 */
#define DSKMAZB 5  	/* OBJECT in TREE #1 */
#define DSKHRAJB 8  	/* OBJECT in TREE #1 */
#define DSKPISB 9  	/* OBJECT in TREE #1 */
#define BLKJEDNI 43  	/* OBJECT in TREE #0 */
#define SELNAZT 1  	/* OBJECT in TREE #3 */
#define SEL11B 15  	/* OBJECT in TREE #3 */
#define SEL21B 28  	/* OBJECT in TREE #3 */
#define SEL1PB 27  	/* OBJECT in TREE #3 */
#define SEL2PB 40  	/* OBJECT in TREE #3 */
#define CTIORCHI 57  	/* OBJECT in TREE #0 */
#define PISORCHI 58  	/* OBJECT in TREE #0 */
#define SELRAMB 14  	/* OBJECT in TREE #3 */
#define EDITNASI 59  	/* OBJECT in TREE #0 */
#define ORCHT 6  	/* OBJECT in TREE #0 */
#define NSEKTITT 1  	/* OBJECT in TREE #13 */
#define CLORCHA 41  	/* STRING */
#define DELNASA 42  	/* STRING */
#define DELSEKA 43  	/* STRING */
#define EDNASFS 15		/* FREE STRING */
#define TEMPOT 10  	/* OBJECT in TREE #6 */
#define BLKODZNI 46  	/* OBJECT in TREE #0 */
#define HLASCT 8  	/* OBJECT in TREE #7 */
#define REPET 7  	/* OBJECT in TREE #15 */
#define ZAHRSI 31  	/* OBJECT in TREE #0 */
#define ZAHRPI 30  	/* OBJECT in TREE #0 */
#define JINYBKFS 16		/* FREE STRING */
#define NOTYI 88  	/* OBJECT in TREE #0 */
#define NOVAI 21  	/* OBJECT in TREE #0 */
#define DEFPISFS 17		/* FREE STRING */
#define DSKPARTB 6  	/* OBJECT in TREE #1 */
#define SELALLI 45  	/* OBJECT in TREE #0 */
#define STATUSD 19  	/* TREE */
#define STATUSI 34  	/* OBJECT in TREE #0 */
#define STAOKB 18  	/* OBJECT in TREE #19 */
#define STACANB 19  	/* OBJECT in TREE #19 */
#define STARAMT 6  	/* OBJECT in TREE #19 */
#define STAPARTT 15  	/* OBJECT in TREE #19 */
#define STASKLT 11  	/* OBJECT in TREE #19 */
#define STANASTT 17  	/* OBJECT in TREE #19 */
#define DESKT 3  	/* OBJECT in TREE #0 */
#define ABOUTI 12  	/* OBJECT in TREE #0 */
#define SELTAH 11  	/* OBJECT in TREE #3 */
#define SELDO 12  	/* OBJECT in TREE #3 */
#define SELUP 13  	/* OBJECT in TREE #3 */
#define OTESKLFS 18		/* FREE STRING */
#define ULOSKLFS 19		/* FREE STRING */
#define CTINASFS 20		/* FREE STRING */
#define ULONASFS 21		/* FREE STRING */
#define VYBNASFS 22		/* FREE STRING */
#define DEFNASFS 23		/* FREE STRING */
#define ABOUT 2  	/* TREE */
#define DSKMSKBB 2  	/* OBJECT in TREE #2 */
#define DSMIMGBB 3  	/* OBJECT in TREE #2 */
#define TOOLBFS 24		/* FREE STRING */
#define AVERZET 5  	/* OBJECT in TREE #2 */
#define ADATUMT 8  	/* OBJECT in TREE #2 */
#define TONOKB 8  	/* OBJECT in TREE #4 */
#define TONDURPD 20  	/* TREE */
#define TONDRPDT 4  	/* OBJECT in TREE #4 */
#define TONMLPDT 6  	/* OBJECT in TREE #4 */
#define DURCI 8  	/* OBJECT in TREE #20 */
#define TONMOLPD 21  	/* TREE */
#define MOLAI 8  	/* OBJECT in TREE #21 */
#define STEREOD 9  	/* TREE */
#define STEOKB 15  	/* OBJECT in TREE #9 */
#define STRSLBB 7  	/* OBJECT in TREE #9 */
#define STRBKBB 6  	/* OBJECT in TREE #9 */
#define STRRTBB 8  	/* OBJECT in TREE #9 */
#define STRLFBB 5  	/* OBJECT in TREE #9 */
#define STRLFTB 11  	/* OBJECT in TREE #9 */
#define STRSLTB 13  	/* OBJECT in TREE #9 */
#define STRBKTB 12  	/* OBJECT in TREE #9 */
#define STRRTTB 14  	/* OBJECT in TREE #9 */
#define STERLFS 26		/* FREE STRING */
#define STERPFS 27		/* FREE STRING */
#define CENDNASA 55  	/* STRING */
#define CEVNORA 56  	/* STRING */
#define CENASFA 57  	/* STRING */
#define STEREOI 65  	/* OBJECT in TREE #0 */
#define HRAPOST 11  	/* OBJECT in TREE #18 */
#define HRAPLYB 5  	/* OBJECT in TREE #18 */
#define HRAREWB 6  	/* OBJECT in TREE #18 */
#define HRAFWDB 7  	/* OBJECT in TREE #18 */
#define HRAENDB 8  	/* OBJECT in TREE #18 */
#define HRAOPAKB 9  	/* OBJECT in TREE #18 */
#define LOKGLOBA 58  	/* STRING */
#define HRAMKANT 13  	/* OBJECT in TREE #18 */
#define TONASD 23  	/* TREE */
#define TON1B 1  	/* OBJECT in TREE #23 */
#define TON1N 3  	/* OBJECT in TREE #23 */
#define TON2B 4  	/* OBJECT in TREE #23 */
#define TON10B 28  	/* OBJECT in TREE #23 */
#define TONFS 25		/* FREE STRING */
#define PRINASFS 6		/* FREE STRING */
#define DSPERRA 59  	/* STRING */
#define SNDERRA 60  	/* STRING */
#define DNEUZA 61  	/* STRING */
#define SAVECFGI 35  	/* OBJECT in TREE #0 */
#define OKTRELB 7  	/* OBJECT in TREE #8 */
#define OKTABSB 8  	/* OBJECT in TREE #8 */
#define DURMOLPD 22  	/* TREE */
#define OHLASI 24  	/* OBJECT in TREE #0 */
#define ZADLEGB 13  	/* OBJECT in TREE #12 */
#define STAPOP1T 12  	/* OBJECT in TREE #19 */
#define HRAPOPT 2  	/* OBJECT in TREE #18 */
#define STAPOP2T 13  	/* OBJECT in TREE #19 */
#define INCSELA 62  	/* STRING */
#define NAJDIRAD 14  	/* TREE */
#define NRACIST 3  	/* OBJECT in TREE #14 */
#define NRAOKB 4  	/* OBJECT in TREE #14 */
#define NAJDIRAI 52  	/* OBJECT in TREE #0 */
#define IMPORTI 23  	/* OBJECT in TREE #0 */
#define SHUPI 54  	/* OBJECT in TREE #0 */
#define SHDOI 55  	/* OBJECT in TREE #0 */
#define NONEXPA 64  	/* STRING */
#define NOEXPOA 63  	/* STRING */
#define EDNSOU3T 8  	/* OBJECT in TREE #16 */
#define EDNSOU4T 9  	/* OBJECT in TREE #16 */
#define EDNOKB 10  	/* OBJECT in TREE #16 */
#define EDNCANB 11  	/* OBJECT in TREE #16 */
#define EFFPARD 10  	/* TREE */
#define EFFABAKB 3  	/* OBJECT in TREE #10 */
#define EFFBBAKB 5  	/* OBJECT in TREE #10 */
#define MIXERD 11  	/* TREE */
#define EFSBAK1B 4  	/* OBJECT in TREE #11 */
#define EFSBAK2B 6  	/* OBJECT in TREE #11 */
#define EFSBAK3B 8  	/* OBJECT in TREE #11 */
#define EFSBAK4B 10  	/* OBJECT in TREE #11 */
#define EFSTXT1T 12  	/* OBJECT in TREE #11 */
#define EFSTXT2T 13  	/* OBJECT in TREE #11 */
#define EFSTXT3T 14  	/* OBJECT in TREE #11 */
#define EFSTXT4T 15  	/* OBJECT in TREE #11 */
#define EFSOKB 16  	/* OBJECT in TREE #11 */
#define EFFOKB 7  	/* OBJECT in TREE #10 */
#define EFSAGRPB 2  	/* OBJECT in TREE #11 */
#define EFSBGRPB 18  	/* OBJECT in TREE #11 */
#define MIXERI 61  	/* OBJECT in TREE #0 */
#define EFEKTI 67  	/* OBJECT in TREE #0 */
#define LISTI 32  	/* OBJECT in TREE #0 */
#define LISTD 17  	/* TREE */
#define LSTNEWB 9  	/* OBJECT in TREE #17 */
#define LSTINSB 10  	/* OBJECT in TREE #17 */
#define LSTLOADB 11  	/* OBJECT in TREE #17 */
#define LSTSAVEB 12  	/* OBJECT in TREE #17 */
#define LSTPREVB 3  	/* OBJECT in TREE #17 */
#define LSTNEXTI 4  	/* OBJECT in TREE #17 */
#define LSTPLAYB 5  	/* OBJECT in TREE #17 */
#define LSTSTOPB 6  	/* OBJECT in TREE #17 */
#define LSTNUMT 7  	/* OBJECT in TREE #17 */
#define LSTPLYFS 28		/* FREE STRING */
#define LSTSTPFS 29		/* FREE STRING */
#define LSTNAMT 8  	/* OBJECT in TREE #17 */
#define STABENT 9  	/* OBJECT in TREE #19 */
#define FALCONLA 65  	/* STRING */
#define PLAYLSFS 30		/* FREE STRING */
